added more emojis
mumuki/mumukit-content-type pull request #3
Opened 2017-07-17 19:26 UTC by fedescarpa

2017-07-19 12:56 UTC, flbulgarelli requested changes
Looks good, but please notice that we are listing emojis that are not present in bibliotheca. E.g: 

* `thinking_face` is not here https://github.com/mumuki/mumuki-bibliotheca/tree/master/src/assets/emojis. :thinking: 
* Neither is `woman_woman_boy_boy` :family_woman_woman_boy_boy: .

2017-07-19 13:01 UTC, flbulgarelli requested changes

2017-07-19 13:01 UTC, flbulgarelli commented on lib/mumukit/content_type/md_emoji.rb
> +    man-woman-boy man-woman-boy-boy man-woman-girl man-woman-girl-boy man-woman-girl-girl man_in_business_suit_levitating man_with_gua_pi_mao
I see some inconsistencies in naming: some emojis are `snake_case` , while others are `dash-case`. 

All them should be `snake_case`.

2017-07-19 13:01 UTC, flbulgarelli commented on lib/mumukit/content_type/md_emoji.rb
> +    taco tada tanabata_tree tangerine taurus taxi tea telephone telephone_receiver telescope tennis tent the_horns thermometer thinking_face
This is weird: `thinking_face` is not actually rendered by github (:thinking_face:), but :thinking: is. 

Moreover, `thinking` is not present in this set. 

This is just an example, there may be more inconsistencies.

2017-07-19 13:02 UTC, flbulgarelli commented
Also, an extra question: is there a full open-source emojis set we can use?

2017-07-19 13:08 UTC, flbulgarelli commented
Please check `wget https://api.github.com/emojis`

2017-09-20 14:04 UTC, flbulgarelli commented
Related to https://github.com/mumuki/mumuki-bibliotheca/issues/80

2017-10-31 15:22 UTC, fedescarpa commented
We need to remove md-emoji

2017-10-31 15:22 UTC, closed without merging